apiVersion: apps/v1
kind: Deployment
metadata:
  name: league
  labels:
    app: league
spec:
  replicas: 1
  selector:
    matchLabels:
      app: league
  template:
    metadata:
      labels:
        app: league
    spec:
      containers:
      - name: league
        image: docker.io/schuermannator/league-arm
        ports:
        - containerPort: 8080
        env:
        - name: RIOTAPIKEY
          value: 
              #- name: GIN_MODE
              #value: release

---

kind: Service
apiVersion: v1
metadata:
  name: league
spec:
  selector:
    app: league
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
